### PR TITLE
Add saving of disk_init_helper data with timestamps

### PR DESCRIPTION
**Pull request by imarkov-storpool**
Sometimes useful for investigations in the internal testing lab.

### CODE REVIEW

**Review by netcho — COMMENTED** [review]
I'm happy overall with how the change looks. However, it came to my mind that it might be beneficial to have the option to copy the previously generated JSON files for production deployments as well. I suggest we add a variable `sp_backup_disk_init_config` with a default value of `False` in favor of `sp_testing_lab`. This way, when we need to debug something, we can just set `sp_backup_disk_init_config` to `True`.

P.S. The name of the variable is subject to change, this is the first name that came to mind.

**Comment by imarkov-storpool** [comment]
Sounds reasonable and the name is OK, see new commit.

**Review by netcho — APPROVED** [review]
Looks good to me, feel free to merge it.

**Comment by imarkov-storpool** [comment]
I just changed the way commands are saved - they are written as arrays (the way Ansible sees them) so you don't have to manually reconstruct the parts where options have strings with spaces as values (e.g. `--ssd-args "--no-notify --force-ssd y --test-override no -o 540000 -e 2160000"`). The quotes were getting lost when piping the array through `join(" ")`.

**Comment by netcho** [comment]
If you have it tested, feel free to merge.

**Pull request merged**
