### PR TITLE
we need to leave more memory (4G) to the kernel on machines with >1.5TB RAM

### PR DESCRIPTION
**Pull request by avladimirov-storpool**

### CODE REVIEW

**Comment by krokodilerian** [comment]
Can you also push this to the storpool branch in http://github.com/storpool/memtester ?

**Comment by krokodilerian** [comment]
Can you also push this to the storpool branch in http://github.com/storpool/memtester ?

**Comment by krokodilerian** [comment]
Can you also push this to the storpool branch in http://github.com/storpool/memtester ?

**Comment by avladimirov-storpool** [comment]
I will :)

**Comment by avladimirov-storpool** [comment]
Actually, I can't. I don't have permissions.

**Pull request merged**
